### ISSUE TITLE
I want to make my own ALE models for DQN Reinforce Learning using my video file input.

### ISSUE THREAD

**Issue by bemoregt** [mgbellemare/Arcade-Learning-Environment#177]
Hi,

I want to make my own ALE models for DQN Reinforce Learning using my video file input.

In video images, there are class labels in the corner for supervised training.
How can I make my own ALE model?

Thank you in advances.

**Comment by mgbellemare** [comment]
Hi @bemoregt , can you be more specific? What kind of model are you trying to build?

**Comment by bemoregt** [comment]
No, not specific.

I just want to DQN ReinforceLearing with my video file.

I think project that can detecting the caption scene in video files.

But I don't know the using method of ALE with video file.

I was ready to edit labels caption in video file's corner for supervised learning.

**Comment by mgbellemare** [comment]
If you want to record videos with ALE, you can use the option --record_screen_dir=my_record_path . See

``doc/examples/videoRecordingExample.cpp''

for an example. ALE doesn't provide the DQN agent, so that is something you will have to find elsewhere. There are a number of re-implementations available online.
