### ISSUE TITLE
Installation instructions for windows?

### ISSUE THREAD

**Issue by pligor** [mgbellemare/Arcade-Learning-Environment#187]
In readme.md at the quick start section there are only instruction on how to install ALE on a linux system.

Windows are not supported? How to install on windows 7? (already installed opencv successfully)
(Interested in the python interface)

**Comment by mgbellemare** [comment]
I don't use Windows myself, but I know many people have successfully used the following port for Visual Studio:

https://github.com/Islandman93/Arcade-Learning-Environment

Alternatively, it should be possible to run ALE in Cygwin, although again I haven't tried.

One thing I should point out is that the Python interface still needs the C++ ALE, so that having a Python interpreter isn't sufficient.

Best,
- Marc

**Comment by mgbellemare** [comment]
Partially addressed in #206
