### ISSUE TITLE
Can't find multi-agent config 

### ISSUE THREAD

**Issue by stefbaby** [mgbellemare/Arcade-Learning-Environment#242]
Hi,

I am working on multi-agent RL as part of my course project and thinking of experimenting with pong environment as suggested in the paper "Multi-Agent Reinforcement Learning: a critical survey". Multi- agent setting is supported well in pong as the authors mention. But I can't find configuration for multi player setting in the manual or ale_python_interface here. Could you direct me to right set of files or give an example on how I can interact in an environment with more than one player?

Essentially I want to do the following with Pong:

reward1,reward2 = env.step(action1, action2)

**Comment by mgbellemare** [comment]
Hi,

This isn't supported directly in ale_interface.cpp. However,
ALEInterface::act()
<https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/ale_interface.cpp#L256>
actually lets you pass in two actions, so it shouldn't be too hard to make
things work.

Previously there was no multiplayer support because this requires selecting
the right mode in most games. It's still not supported through the modes
interface, but again with relatively little poking around
<https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/games/supported/Pong.cpp#L113>
you should be able to change the mode selection code to select a 2-player
mode.

Now, the thing that *is* missing is the reward for the second player. In
some games like Pong the reward of one player is the negative of the
other's; but in general that won't be the case. Unfortunately there's no
easy way to return two rewards, but here's where it's computed
<https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/games/supported/Pong.cpp#L36>
e.g. in Pong. For your purposes there are a few ways you can hack the code
to make it do what you want reasonably easily.

Best,
- Marc

**Comment by JesseFarebro** [comment]
#350 seeks to implement a multi-agent interface. Also, see [PettingZoo](https://www.pettingzoo.ml/atari) for a wrapper around this interface / more info on supported games.
