### ISSUE TITLE
Code for the paper "The Arcade Learning Environment: An Evaluation Platform for General Agents" ?

### ISSUE THREAD

**Issue by alcinos** [mgbellemare/Arcade-Learning-Environment#260]
Hi,

It seems that the code was previously available from the website: https://web.archive.org/web/20140310115059/http://www.arcadelearningenvironment.org/publications/the-arcade-learning-environment-an-evaluation-platform-for-general-agents

Now that the site is down, is there any way to get this code?
I'm interested in particular by the BASS and DISCO features, which don't seem to be available on that repo, unless I'm missing something.

Thanks in advance

**Comment by mgbellemare** [comment]
Hi,

I've looked around and unfortunately that code is gone. BASS is not too difficult to reproduce: start with Basic by iterating through pixels, and recording presence colours in each tile. Then take the pair-wise products.

For speed, you can use John Langford's VW trick for generating all pairs of active features (it's been a while since I looked at this, though). The DISCO features never worked very well...
