### ISSUE TITLE
Screen values not working on Windows Subsystem Linux

### ISSUE THREAD

**Issue by focussash** [mgbellemare/Arcade-Learning-Environment#318]
Hey guys, I am working with ALE under WSL ubuntu, and encountered a problem where ale.getScreen(), ale.getScreenGrayscale() and ale.getScreenRGB() all return 0s?

I followed the python tutorial when invoking these methods, namely:

screen_data = np.zeros(screen_width*screen_height,dtype=np.uint8)
ale.getScreen(screen_data)

And, for RGB:

(screen_width,screen_height) = ale.getScreenDims()
screen_data = np.zeros(screen_widthscreen_height3,dtype=np.uint32)
ale.getScreenRGB(screen_data)

All of the above gives me vectors of all 0s, and I verified that it was not because ALE did not modify the initialized 0s; rather, even if I arbitraily initialized some values to be non-zero, after applying getScreenRGB all the values become 0 again, showing that ALE somehow thinks the screen should be... blank??

All other ALE attributes work normally, such as RAM, lives, mode, even screen dimensions, just not the screen values

I know that WSL does not support graphical display, which means SDL is not supported. However, would that also cause the getScreen functions to malfunction?

**Comment by JesseFarebro** [comment]
Hi,

You don't need SDL for `getScreen*` functions. I don't believe any of us have access to a Windows machine in order to reproduce this issue. But I notice a couple of issues off the bat.

`getScreenDims` returns the `(width, height)` tuple, but `getScreen*` expects a numpy array with shape `(height, width, channels)`. Also the call to `getScreenRGB` should have a `uint8` array as the colour values are still 1 byte. It should look like:

```python
(width, height) = ale.getScreenDims()

grayscale = np.zeros((height, width, 1), dtype=np.uint8)
ale.getScreenGrayscale(grayscale)

rgb = np.zeros((height, width, 3), dtype=np.uint8)
ale.getScreenRGB(rgb)
```

Sorry if that wasn't clear in the documentation. We will be releasing a new Python wrapper with better error checking and documentation.

**Comment by focussash** [comment]
Thanks for the classification! For that part of code I provided I found them from one of the ALE tutorials available so it might have been outdated.
With that said, I retried with what you suggested but it seems the issue persisted, however I had some issues while installing ALE within WSL in the first place so it might had been related to those... In any case, switching to a Linux machine did solve all the problem haha, so thanks again for your time and clarification
