### ISSUE TITLE
Non-standard observation sizes

### ISSUE THREAD

**Issue by weepingwillowben** [mgbellemare/Arcade-Learning-Environment#361]
Quite a few of the newer games have non-standard observation sizes, in that they draw images that are not (160x210). 

These games are:

```
adventure (160, 250)
air_raid (160, 250)
carnival (160, 214)
journey_escape (160, 230)
keystone_kapers (160, 250)
king_kong (160, 250)
klax (160, 250)
laser_gates (160, 250)
mr_do (160, 250)
pacman (160, 250)
pooyan (160, 220)
sir_lancelot (160, 250)
space_war (160, 250)
```

Presumably you could still use downsampling in postprocessing to get these images to the same dimensions, but I was wondering if there was a standard way of handling this problem.

**Comment by justinkterry** [comment]
@tkoeppe These are mostly environments you added, I believe

**Comment by tkoeppe** [comment]
@kieranhj: could you take a look please?

**Comment by kieranhj** [comment]
The current ALE interface makes no guarantees about the RGB observation size, it merely returns the frame buffer from the TIA implementation in the underlying Stella emulator. For NTSC games this is _typically_ 160x210 and for PAL games usually 160x250. However because of the way the Atari 2600 generates a video signal, the vertical resolution is effectively determined by however many scanlines of time the ROM code requests the TIA to generate pixels.

From the above list, the following games are PAL ROMs:
```
adventure (160, 250)
air_raid (160, 250)
king_kong (160, 250)
klax (160, 250)
space_war (160, 250)
```
Whilst the remaining games are NTSC ROMs with non-typical vertical resolution:
```
carnival (160, 214)
journey_escape (160, 230)
keystone_kapers (160, 250)
laser_gates (160, 250)
mr_do (160, 250)
pacman (160, 250)
pooyan (160, 220)
sir_lancelot (160, 250)
```
These are sometimes specified in the Stella ROM properties file, stella.pro. For example, carnival:
```
"Cartridge.MD5" "028024fb8e5e5f18ea586652f9799c96"
"Cartridge.Manufacturer" "Coleco"
"Cartridge.ModelNo" "2468"
"Cartridge.Name" "Carnival (1982) (Coleco)"
"Cartridge.Rarity" "Uncommon"
"Display.YStart" "26"
"Display.Height" "214"
""
```
But unfortunately not always, for example sir_lancelot:
```
"Cartridge.MD5" "4c8970f6c294a0a54c9c45e5e8445f93"
"Cartridge.Manufacturer" "Xonox"
"Cartridge.ModelNo" "99006"
"Cartridge.Name" "Sir Lancelot (1983) (Xonox) [a1]"
"Cartridge.Rarity" "Extremely Rare"
""
```
In this case the developer has programmed the TIA to output pixels for 250 scanlines of the ~263 possible for an NTSC signal, either by design to overscan the screen, possibly for ease of support with PAL. Hard to say.

The dimensions of the RGB observation are available through the interface, but if we wish to guarantee that is always of fixed size, that would be an interface change decision for the ALE owners.

**Comment by tkoeppe** [comment]
@weepingwillowben, @justinkterry: How would you like the system to behave? As Kieran said, I don't think there was ever a promise that the scren sizes would take on any particular value, and that's why they are queryable at runtime. I'm inclined to call this "working as intended"; what do you think?

**Comment by weepingwillowben** [comment]
Since this feature is a product of the ROMs themselves, then sure. It was just confusing because all of the original games had this shape, so there was some unspoken assumption that all of the games would always have this shape. Obviously that was not a well defined assumption, just a point of confusion. 

Thanks for clearing it up.

I guess I will close this issue.

**Comment by justinkterry** [comment]
I was just having a follow up discussion about this with Ben. For certain games like Tennis, but _especially_ space war, part of this problem is that part of the observation space is just black padding that's an artifact of the ROMS. Would you guys be open to a PR that natively crops this? Especially for space war it's kind of ridiculous.

**Comment by justinkterry** [comment]
@tkoeppe

**Comment by weepingwillowben** [comment]
For reference, here are gifs of space war and tennis, respectively.

![atari_space_war](https://user-images.githubusercontent.com/10835669/115975641-6a958b80-a534-11eb-9500-1a2c4e549d19.gif)

![atari_tennis](https://user-images.githubusercontent.com/10835669/115975652-87ca5a00-a534-11eb-8380-0522e777a11b.gif)
