### ISSUE TITLE
Suggestion: keep optimization private

### ISSUE THREAD

**Issue by cg31** [mgbellemare/Arcade-Learning-Environment#372]
In th CMakeLists.txt, the optimazation options are declared as public:

```
target_compile_options(ale PUBLIC -O3 -fPIC)

# Compiler specific flags
target_compile_options(ale
  PUBLIC
    $<$<CXX_COMPILER_ID:GNU,Clang,AppleClang>:-Wall -Wunused -fomit-frame-pointer>
)
```
when an option is public, it will be propagated to applications. This will be a problem when users want to compile a debuggable application using -O0 and with frame pointer.

So it is better to declare them as private:

```
target_compile_options(ale PRIVATE -O3 -fPIC)

# Compiler specific flags
target_compile_options(ale
  PRIVATE
    $<$<CXX_COMPILER_ID:GNU,Clang,AppleClang>:-Wall -Wunused -fomit-frame-pointer>
)
```

**Comment by JesseFarebro** [comment]
Thanks for pointing this out, I had a misconception as to how `PUBLIC` worked. For some reason, I thought `PUBLIC` would propagate `_INTERFACE` to the dependencies' local variable instead of its `_INTERFACE` counterpart. 
I believe the subdirectory-based options (`add_compiler_options`, `CMAKE_CXX_STANDARD`, etc.) should work just fine for our use case (#375).
