### ISSUE TITLE
make -j 4 failed

### ISSUE THREAD

**Issue by willtop** [mgbellemare/Arcade-Learning-Environment#402]
Hello all. I am new to ALE, just trying to build ALE to have SDL support. I have been stuck on this error for a day.
After running "cmake -DUSE_SDL=ON -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=ON ." seemingly without error, I received the fatal errors when followed by running "make-j 4":
...
[ 18%] Building CXX object src/CMakeFiles/ale.dir/emucore/CartUA.cxx.o
[ 18%] Building CXX object src/CMakeFiles/ale.dir/emucore/Console.cxx.o
In file included from /home/will/Arcade-Learning-Environment/src/emucore/Console.cxx:42:0:
/home/will/Arcade-Learning-Environment/src/emucore/OSystem.hxx:24:22: fatal error: filesystem: No such file or directory
compilation terminated.
src/CMakeFiles/ale.dir/build.make:484: recipe for target 'src/CMakeFiles/ale.dir/emucore/Console.cxx.o' failed
make[2]: *** [src/CMakeFiles/ale.dir/emucore/Console.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:259: recipe for target 'src/CMakeFiles/ale.dir/all' failed
make[1]: *** [src/CMakeFiles/ale.dir/all] Error 2
Makefile:159: recipe for target 'all' failed
make: *** [all] Error 2

I installed SDL via "sudo apt-get install libsdl1.2-dev", and cmake via the newest sh file from cmake.org (instead of "sudo apt-get cmake", nonetheless I don't think this would cause anything wrong).

Any idea about how to fix the problem? Sincere thanks!

Meanwhile, I am also aware of the atari-py from openai that one can directly install with pip. I tried that option and successfully installed conveniently. However I'd like to see the game console, and I think there is no way I could have SDL enabled through such direct pip install. Is that true? If I really can't get SDL working, is there way around to see the game console?

**Comment by JesseFarebro** [comment]
So the problem you're encountering is due to your compiler. What version of Ubuntu are you running? Can you report your gcc version, i.e., `gcc --version`.

If you want to be able to view the display you have a couple of options.

1. Update your compiler so that it supports C++17 and hence the filesystem API (that's the error you're encountering).
2. You can try out a nightly build of `ale-py` which distributes SDL2 and doesn't involve compiling the ALE itself, i.e.,
`
pip install -i https://test.pypi.org/simple/ ale-py==0.6.2.dev20201229
`
2. You can use OpenAI Gym and call the `.render('human')` function on the environment.

**Comment by willtop** [comment]
Hello Jesse, many appreciation for your reply!

It is indeed the problem that my gcc is too old. I have Ubuntu version: 16.04.3 LTS, and gcc version: 5.4.0. Now I have updated it to gcc-9, the make command runs successfully.

However, later when I run `pip install --usr .`, I encountered the following error:

> Building wheels for collected packages: ale-py
  Building wheel for ale-py (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/will/.conda/envs/pytorch/bin/python /home/will/.conda/envs/pytorch/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpfaajwy8k
       cwd: /tmp/pip-req-build-6p8i62on
  Complete output (6 lines):
  running bdist_wheel
  running build
  running build_ext
  cmake /tmp/pip-req-build-6p8i62on -DCMAKE_BUILD_TYPE=Release -DBUILD_CPP_LIB=OFF -DBUILD_PYTHON_LIB=ON -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=/tmp/pip-req-build-6p8i62on/build/lib.linux-x86_64-3.7/ -DPython3_EXECUTABLE=/home/will/.conda/envs/pytorch/bin/python -GNinja
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-6p8i62on/CMakeCache.txt is different than the directory /home/will/Arcade-Learning-Environment where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  error: command 'cmake' failed with exit status 1
  ----------------------------------------
>  ERROR: Failed building wheel for ale-py
Failed to build ale-py
ERROR: Could not build wheels for ale-py which use PEP 517 and cannot be installed directly

I found this being asked before and you replied to try with `python setup.py bdist_wheel`, which I tried (with python3), and received the following:
> CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
error: command 'cmake' failed with exit status 1

I see the error msgs include suggestions, however I don't fully understand it and thus don't think trying blindly would be a good idea. Any idea on how to resolve the issue?

Please let me know any information you'd like about my system. Many thanks again for the help!

**Comment by JesseFarebro** [comment]
I believe your error is probably due to you running `cmake` in the root directory of the repository. You can either try deleting all the temporary generated CMake files OR just try doing a fresh build by recloning the repository and building from there:

```sh
git clone https://github.com/mgbellemare/Arcade-Learning-Environment && cd Arcade-Learning-Environment
pip install --user .
```

In the future, when building CMake projects try to always build them from a separate folder, e.g., `mkdir build && cd build && cmake ../` so the CMake temporary files aren't generated in the project root.

Also, currently, the Python build disables SDL support, this will change with the addition of SDL2 in #368. For the time being if you want SDL support in Python it's probably easiest to edit `src/CMakeLists.txt` and set `USE_SDL` to `ON`.

**Comment by willtop** [comment]
Hello Jesse, thanks again for your help! Now I've successfully built, installed, and can visualize the game console!
As I am new to ALE, I would highly appreciate if you could help by clarifying the following questions that have been bothering me:

1. How to obtain the ROMs for atari games? Is it already within this ALE repo (I searched throughout and couldn't find any ROMs). I am currently using ROMs from `http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html`. However the set is too comprehensive, and I don't know which 57 games are the ones the deepmind DQN papers used (which are the ones I am trying to test over).
2. What's the difference between this ALE repo `https://github.com/mgbellemare/Arcade-Learning-Environment`, and the atari-py from OpenAI `https://github.com/openai/atari-py`. Is that openai atari-py one just a pre-compiled executable version of this repo (thus we can't use it if want to use SDL), or there are other differences? Essentially, as a researcher working on DQN to be tested over atari games (like the deepmind scientists), which is the best one to go for?
      2.1 As you previously kindly pointed out:  `You can use OpenAI Gym and call the .render('human') function on the environment.`
           For the atari-py from OpenAI, did they somehow convert the atari games as OpenAI environments, and therefore all openai environment methods are supported on the atari games? Is that a feature this ALE repo is lacking? 
3. Regarding your SDL2 comment: I did try to install libsdl2 at the beginning, which triggered `SDL directory not found` error, so I returned to libsdl1.2 (also what the manual used). You mentioned the support is discontinued, however would it affect me using this in anyways (essentially what's the difference between using SDL1.2 and SDL2 with ALE)?
4. What's the difference between `edit src/CMakeLists.txt and set USE_SDL to ON` and `-DUSE_SDL=ON` option when calling cmake? I did both, but find it confusing. 

Sincere thanks again for your patience and consideration!

**Comment by JesseFarebro** [comment]
> 1. How to obtain the ROMs for atari games? Is it already within this ALE repo (I searched throughout and couldn't find any ROMs). I am currently using ROMs from `http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html`. However the set is too comprehensive, and I don't know which 57 games are the ones the deepmind DQN papers used (which are the ones I am trying to test over).

There's not a single source for ROMs but they shouldn't be too hard to find online. For the best compatibility try to match the MD5 sum of the ROM you download with those specified in `md5.txt` in the root of the repository. We'll eventually have a better way to manage ROM imports and distribution, see #382.


> 2. What's the difference between this ALE repo `https://github.com/mgbellemare/Arcade-Learning-Environment`, and the atari-py from OpenAI `https://github.com/openai/atari-py`. Is that openai atari-py one just a pre-compiled executable version of this repo (thus we can't use it if want to use SDL), or there are other differences? Essentially, as a researcher working on DQN to be tested over atari games (like the deepmind scientists), which is the best one to go for?

The main difference was that atari-py distributed all the ROMs in a pre-compiled wheel so you could easily `pip install atari-py` instead of manually compiling the ALE. OpenAI removed the ROMs from the repository and now there aren't any major differences, we're working on deprecating atari-py in Gym in favor of the official repository. There's been ongoing work towards this and it's almost complete.

>    2.1 As you previously kindly pointed out:  `You can use OpenAI Gym and call the .render('human') function on the environment.`
>    For the atari-py from OpenAI, did they somehow convert the atari games as OpenAI environments, and therefore all openai environment methods are supported on the atari games? Is that a feature this ALE repo is lacking?

Yes, in Gym they "register" specific games with the environment ID you've probably seen. The Gym `render()` function just takes RGB observations from the ALE and displays them using pygame.

> 3. Regarding your SDL2 comment: I did try to install libsdl2 at the beginning, which triggered `SDL directory not found` error, so I returned to libsdl1.2 (also what the manual used). You mentioned the support is discontinued, however would it affect me using this in anyways (essentially what's the difference between using SDL1.2 and SDL2 with ALE)?

No, the change to SDL2 is mainly to solve some bugs on certain platforms. SDL support doesn't affect emulation at all, it's solely to display the screen at the user's request.

> 4. What's the difference between `edit src/CMakeLists.txt and set USE_SDL to ON` and `-DUSE_SDL=ON` option when calling cmake? I did both, but find it confusing.

When you run `pip install .` it uses `setuptools` (as defined in `pyproject.toml`) to run `setup.py` to build the Python wheel. If you take a look at `setup.py` you can see we manually bootstrap the cmake build and we specify the build parameters. We currently don't specify `-DUSE_SDL` at all and it defaults to `OFF`. I could have gotten you to edit `setup.py` to specify `-DUSE_SDL=ON` OR edit `src/CMakeLists.txt`, I thought the latter was simpler.

When manually compiling the ALE with cmake, i.e., not via `pip install` you have to specify the CLI parameters yourself and that's where you have the freedom to specify `-DUSE_SDL`.

**Comment by willtop** [comment]
Hello Jesse. Thanks a lot!
Reading your pointer #382 I just have a last couple of questions (My apology! feel free to reply whenever it's convenient for you).
1. Is `gym.make("ale-py:Freeway-v0")` equivalent to ale.loadROM(_ROM_bin_filename_) (also relies on externally downloaded rom bin file?) ? 
2. To find the 57 atari 2600 games in the right version as the games tested by those DQN papers, where should I look for (`http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html` is too exhaustive and I don't know which versions to look for).  

As I am trying `ale-import-roms` and `from ale_py.roms import find_internal_roms`, the commands are not found. So I am assuming the updates are yet in effective and will be upcoming?

Sorry again for any inconvenience. No rush in replying.

**Comment by JesseFarebro** [comment]
No problem, it's not an inconvenience. 

> 1. Is `gym.make("ale-py:Freeway-v0")` equivalent to ale.loadROM(_ROM_bin_filename_) (also relies on externally downloaded rom bin file?) ?

More or less, the Gym ID's bring along with them some legacy settings for backwards compatibility. By the time these changes are merged, there will be some updated documentation. In the future `gym.make('ale-py: ... ')` will rely on finding ROMs using the two specified methods outlined in #382.

> 2. To find the 57 atari 2600 games in the right version as the games tested by those DQN papers, where should I look for (`http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html` is too exhaustive and I don't know which versions to look for).

Yeah, I definitely understand how this can be a problem. I believe that archive should contain the ROMs we support. You could do something like this to find them:

```sh
# Extract the Atari mania archive into ROMS
find ROMS -type f -exec md5sum "{}" \; > atarimania-md5.txt
awk 'FNR=NR{a[$1];next}($1 in a){print}' md5.txt atarimania-md5.txt
```

That should print out all the MD5 matches in the atarimania dump. We support more games now than the original DQN paper so it would be a matter of just matching which games they originally used to the proper ROM in the dump.

> As I am trying `ale-import-roms` and `from ale_py.roms import find_internal_roms`, the commands are not found. So I am assuming the updates are yet in effective and will be upcoming?

Yes, those changes will be available once that PR is merged.

**Comment by willtop** [comment]
Hello Jesse, sounds great! Sincerely appreciate your help all along!

I will go ahead and close this issue now. Thanks again for your kind help!
