### ISSUE TITLE
Proposal: crop black space from observations

### ISSUE THREAD

**Issue by jkterry1** [mgbellemare/Arcade-Learning-Environment#415]
Some of the ROMS added, such as space war and tennis, include massive amounts of black space in the observations they return. These either have to be removed by learning code or result in wasted compute time. While I understand the ethos of the ALE is to return the Atari games in as pure a form as possible, which I believe it why this is done now, these giant black borders generally are not actually displayed to computers via Atari consoles (I actually own one). I accordingly would propose they be removed.

**Comment by justinkterry** [comment]
#361 is a related issue.

**Comment by JesseFarebro** [comment]
Those black borders are an artifact of how the console displays an image to the screen. From what I understand these black bars on the top and left of the screen are necessary for the console to display multiple moving sprites on the screen at once. I don't fully understand the details but these artifacts are most definitely visible on the Atari 2600. For example, in Space Invaders, before you start the game the screen has a green tint and you're able to see these artifacts on the same rows where there are moving sprites:

![Space Invaders (1980) (Atari)](https://user-images.githubusercontent.com/1377567/118411347-546d7d80-b651-11eb-87c4-01054f3dc4f4.png)

If you spend long enough on Youtube you can find someone playing Space Invaders with a CRT and [you'll observe the same artifacts](https://youtu.be/4kyNU5xR9as?t=117).

Now some games like Tennis have a background that's not black so it seems more noticeable. I also believe that some games found a hack to colour these black areas with a different colour but you'll never see any moving objects in these areas of the screen.

The size difference of the frame buffer between NTSC and PAL ROMs is a completely different issue. I believe there are some workarounds, for example, upstream Stella maintains a fixed frame buffer of 320 x 160 before scaling it to an appropriate resolution for the user's display. I believe they do some type of aspect ratio correction to get it in this standardized resolution. I'll explore this more as I already have some big changes coming from upstream.

I don't think just cropping these observations is a good idea, I don't think there's much to gain by cropping out such a small area. It also introduces other issues. How many games do we do this for, all of them? Do we hardcode different dimensions for each combination of ROM types, e.g., PAL, NTSC, etc.? Most of the games we support have these types of artifacts.

**Comment by justinkterry** [comment]
So I finally got into my office today and could take a look at these on my Atari 2600, and it seems like something strange is going on here to me:

-The space invaders gif in Gym shows black bars on the top and bottom. On my CRT, a black bar only exists on the top, and only on the loading screen like you mentioned (which suggests the only on the loading screen that its not "that" black bar to me)
-The Gym gif for tennis shows black on the bottom, left and a massive one on top. On my CRT, only the black bars on the top and left for Tennis are real, but the one on top is very small.
-The space war gif in PettingZoo has massive black bars on the top and bottom, but on my CRT has no black bar on the bottom and either no bar or a tiny bar on the top.
-The Gym gif of Solaris shows bars on the top/left/bottom, but my CRT only shows it on the left

And so forth. 

I had planned on taking pictures of all this but it turns out that photographing a CRT on an iPhone is extraordinarily difficult. As far as the issue of hard coding dimensions goes, we already hard code a ton of memory registers for each ROM, it doesn't seem particularly implausible or labor intensive to just hard code all these values for either each ROM type, or at least for the specific ROM we're listed as supporting.

Also, on the scale that a lot of Atari environments are run at, it at least seems to me like there would actually be a lot to gain from removing the large amount of unusable observations, especially for environments where the black bars are massive.

**Comment by JesseFarebro** [comment]
So I'm going to close this issue. The reasons are as follows:

1) Cropping the images will lead to even more weird image dimensions. We already don't have a good way to deal with NTSC vs. PAL as opposed to the proper scaling solution in upstream Stella.

2) We want to stay as close to the ground truth emulator as possible. This isn't an ALE bug, this is just how the Atari 2600 displays content.

3) I think your concern stems from visualizing the display. We now have proper scaling support with `display_screen` and there are methods to properly scale the content on the web. See the [image-rendering: pixelated](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) CSS property. Both of these would reduce these artifacts as you had noticed on your TV.
