### ISSUE TITLE
How to reset the environment to choose a random start state for the agent?

### ISSUE THREAD

**Issue by nikhilrayaprolu** [mgbellemare/Arcade-Learning-Environment#421]
I found that some of the papers, especially those that generate [successor features](https://arxiv.org/pdf/1710.11089.pdf) for an environment, create samples using agents with random start states. How can I reset an environment to place the agent at a random start state? Currently, I realized that the agent starts at the same initial state every time I reset.

**Comment by JesseFarebro** [comment]
Hi,

Random starts were used to inject some stochasticity into the ALE as the Atari emulator is fully deterministic. The suggested way to inject stochasticity into the ALE is to now use sticky actions (see [Machado et al. 2018](https://arxiv.org/abs/1709.06009)). The ALE defaults to having sticky actions enabled but you can adjust this with: `ale.setFloat('repeat_action_probability', prob)` where `prob` is the probability of the agent repeating the last action instead of executing the current action.

If you were attempting to reproduce results that use random starts you could just choose a random number of steps to execute before beginning the episode.

Sorry for the delay, hope this helps.
