### ISSUE TITLE
Rendering fails in multiple ways on Pong-v4

### ISSUE THREAD

**Issue by ikamensh** [mgbellemare/Arcade-Learning-Environment#450]
1. Missing dependency pygame?
```
pip install gym[atari]
python -c "import gym; env=gym.make('Pong-v4'); env.render()"
```
-> fails to import pygame

-----

2. no rendering in gym.envs.classic_control
```
pip install gym[atari]
pip install pygame
python -c "import gym; env=gym.make('Pong-v4'); env.render()"
```
->
```
  File "/Users/kai7rng/opt/anaconda3/envs/matari/lib/python3.8/site-packages/gym/envs/atari/environment.py", line 264, in render
    from gym.envs.classic_control import rendering
ImportError: cannot import name 'rendering' from 'gym.envs.classic_control' (/Users/kai7rng/opt/anaconda3/envs/matari/lib/python3.8/site-packages/gym/envs/classic_control/__init__.py)
```

Environment:
MacOs with Python 3.8.5, gym dependencies:
```
ale-py==0.7.4
AutoROM==0.4.2
AutoROM.accept-rom-license==0.4.2
gym==0.23.1
gym-notices==0.0.6
```

**Comment by pseudo-rnd-thoughts** [comment]
Im able to replicate your issue with `pip install gym[atari]` but `pip install pygame` seems to fix it for me

**Comment by JesseFarebro** [comment]
Yes, `env.render()` is broken in the current release of Gym. I'll be releasing another update to fix this on our side.

It's worth noting that we __do not__ recommend you use `env.render()`. Please supply the `render_mode` kwarg to the constructor, e.g.,

```py
env = gym.make('ALE/Breakout-v5', render_mode='human')
```

**Comment by sudislife** [comment]
`gym.make('ALE/Breakout-v5', render_mode = 'human')` also does not work for me, it gives me an Arcade Learning Environment Window which is stuck on not responding and if I try to close it, the kernel dies. (I've waited for the ALE to load for more than 10 mins and it still stays stuck on not responding).

![image](https://user-images.githubusercontent.com/43610610/161425098-e3eb788a-98d7-4413-8c91-dd1f8ed4ed96.png)
![image](https://user-images.githubusercontent.com/43610610/161425254-5268a3ce-17d1-400d-9b42-c61c48278723.png)


I'm getting this by simply running this cell in the jupyter notebook without running any other cells before it...
```
import gym

env = gym.make('ALE/Breakout-v5', render_mode='human')
```

Funny thing is there's this thing which happens when I run this cell after the one above
```
from gym.utils import play

play.play(env, zoom = 3)
```

![image](https://user-images.githubusercontent.com/43610610/161425443-ef249afa-f963-4274-9151-fa8b36778b74.png)

What I want shows up but both windows are completely unresponsive and you have to close it via the task manager.

**My Pip List and installs**

I've already `pip install gym[accept-rom-license]`, `pip install gym[atari]`, `pip install ale-py`, and `pip install pygame`

```
ale-py 0.7.4
argon2-cffi 21.3.0
argon2-cffi-bindings 21.2.0
asttokens 2.0.5
attrs 21.4.0
AutoROM 0.4.2
AutoROM.accept-rom-license 0.4.2
backcall 0.2.0
beautifulsoup4 4.10.0
bleach 4.1.0
certifi 2021.10.8
cffi 1.15.0
charset-normalizer 2.0.12
click 8.1.2
cloudpickle 2.0.0
colorama 0.4.4
cycler 0.11.0
debugpy 1.6.0
decorator 5.1.1
defusedxml 0.7.1
entrypoints 0.4
executing 0.8.3
fonttools 4.31.2
gym 0.23.1
gym-notices 0.0.6
idna 3.3
importlib-metadata 4.11.3
importlib-resources 5.6.0
ipykernel 6.11.0
ipython 8.2.0
ipython-genutils 0.2.0
jedi 0.18.1
Jinja2 3.1.1
jsonschema 4.4.0
jupyter-client 7.2.1
jupyter-core 4.9.2
jupyterlab-pygments 0.1.2
kiwisolver 1.4.2
MarkupSafe 2.1.1
matplotlib 3.5.1
matplotlib-inline 0.1.3
mistune 0.8.4
nbclient 0.5.13
nbconvert 6.4.5
nbformat 5.2.0
nest-asyncio 1.5.4
notebook 6.4.10
numpy 1.22.3
packaging 21.3
pandocfilters 1.5.0
parso 0.8.3
pickleshare 0.7.5
Pillow 9.1.0
pip 21.2.4
prometheus-client 0.13.1
prompt-toolkit 3.0.28
psutil 5.9.0
pure-eval 0.2.2
pycparser 2.21
pygame 2.1.2
Pygments 2.11.2
pyparsing 3.0.7
pyrsistent 0.18.1
python-dateutil 2.8.2
pywin32 303
pywinpty 2.0.5
pyzmq 22.3.0
requests 2.27.1
Send2Trash 1.8.0
setuptools 61.3.1
six 1.16.0
soupsieve 2.3.1
stack-data 0.2.0
terminado 0.13.3
testpath 0.6.0
tornado 6.1
tqdm 4.63.1
traitlets 5.1.1
urllib3 1.26.9
wcwidth 0.2.5
webencodings 0.5.1
wheel 0.37.1
wincertstore 0.2
zipp 3.7.0
```

**Comment by JesseFarebro** [comment]
With `ale-py==0.7.5` we removed `.render(mode="human")`. This will now display a warning and instruct users to use the `render_mode` keyword argument when constructing the environment.
