### ISSUE TITLE
Is it standard to grayscale?

### ISSUE THREAD

**Issue by slerman12** [mgbellemare/Arcade-Learning-Environment#458]
I've been using rgb.

`gym.make(env, obs_type='rgb')`

However, StableBaselines3 uses grayscale.

Which one is preferred/standard?

Thanks.

**Comment by JesseFarebro** [comment]
Hi @slerman12, the standard methodology since the release of DQN is that the agent will observe grayscaled frames, down sampled to 84x84 and stacked in the depth channel with the previous 4 observations.

There's a lot of nuance in the preprocessing stack for the ALE. I would highly suggest using something that's tried and tested. I would recommend looking at:

- [dqn_zoo's `processors.AtariEnvironmentWrapper`](https://github.com/deepmind/dqn_zoo/blob/f011d683529d8d23b017a95194ebbb41a4962fe8/dqn_zoo/processors.py#L405-L577) (this is what I'd consider the gold-standard implementation).
- [Dopamine's `atari_lib.AtariPreprocessing`](https://github.com/google/dopamine/blob/a34615cb611c7c23b63ca7e6fee45331e6e1f912/dopamine/discrete_domains/atari_lib.py#L329-L516)
- [Acme's `atari_wrapper.AtariWrapper`](https://github.com/deepmind/acme/blob/b9ba5953495c76b20b0d7a2e4b2e7301a828b75c/acme/wrappers/atari_wrapper.py#L31-L335)

We provide the option to retrieve RGB observations from `gym.make` but in the future I plan on building the complete preprocessing pipeline into the ALE itself so there isn't all these different postprocessing implementations.

Let me know if you have any other questions about this, I know it can be confusing, the most common questions I receive are around postprocessing.
