### ISSUE TITLE
SDL visualization jitter in Tetris

### ISSUE THREAD

**Issue by mgbellemare** [mgbellemare/Arcade-Learning-Environment#95]
PR #93 introduced Tetris support. Currently the SDL visualization jitters in Tetris, even though the recorded screens (e.g. via the video recording example) are stable.

**Comment by mhauskn** [comment]
I've been able to recreate the observed weirdness. Now looking into the cause(s).

**Comment by mhauskn** [comment]
It should be noted that Stella's display of udibr's Tetris26 also jitters. So I'd say our display screen code may perhaps not be at fault. The original tetris26 (http://www.atari2600homebrew.com/tetris26.html) when played through Stella jitters at a fast enough rate to create a phosphor-blend type effect. It seems the changes that @udibr introduced in his version of Tetris26 render the phosphor blend effect into a jitter (perhaps slower frame rates due to his improvements in randomization?). If you'd like, I can look into why the video recording does not jitter.

**Comment by mgbellemare** [comment]
Ah, I see what this is. The renderer doesn't display colour-averaged
frames, but ScreenExporter (which records what is
sent to the agent) does.

**Comment by mgbellemare** [comment]
Nothing to see here then, thanks for looking into this.
